apiVersion: v1
kind: Service
metadata:
  name: testoke-lb
  namespace: poc-oke
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    oci.oraclecloud.com/internal-load-balancer: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: testoke
  ports:
  - port: 80
    targetPort: 80